version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:ubuntu
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt install -y m4
            opam install menhir dune ounit
      - run:
          name: Build
          command: |
            eval $(opam env)
            cd minimlInterp && dune build
      - run:
          name: Test
          command: |
            eval $(opam env)
            cd minimlInterp && dune runtest
